### ISSUE TITLE
fcitx5，重试？？？

### ISSUE THREAD

**Issue by Mr-Roxe** [debuggerx01/fcitx5_customizer#10]
![image](https://github.com/user-attachments/assets/1a588ec2-42cc-4116-b7e3-a1b3f861baf2)

这正常么？？？我也不知道啊。

**Comment by debuggerx01** [comment]
@Mr-Roxe https://github.com/fcitx/fcitx5/issues/331
参考上面的issue，正确的环境变量应该是fcitx而不是fcitx5，使用fcitx5作为环境变量有可能在一些情况下出现问题，建议改一下。
