### ISSUE TITLE
双拼下面用V键无法进入快捷输入模式

### ISSUE THREAD

**Issue by xiaomingneo** [debuggerx01/fcitx5_customizer#11]
有个小问题：
1、个人喜欢用双拼，但是测试显示只有在全拼/简拼模式下可以用V键触发快捷输入，双拼不行

另外，请教一下
1、翻页键如何设定为 <, 和 >. 键

**Comment by debuggerx01** [comment]
1. 全拼可以用是因为全拼时“v只有作为韵母ü的用途，而且单个ü不代表任何汉字，故不会有v开头的拼音输入序列”，所以可以放心的把v作为触发键。而双拼模式下v可以作为声母使用，很多方案是把v当作zh使用，自然就不好使了。
  ![image](https://github.com/user-attachments/assets/59acf67a-2bcb-4bfd-afbf-389ead99ded9)
  虽然你也可以在设置里打开v触发，但是就不好直接输入类似“中文（小鹤双拼的vswf）”这样的词了。所以我的方案是把键盘右侧的alt修改成可以被用作触发键的键码，然后设置成按下右侧alt键进入快速输入：https://www.debuggerx.com/2023/10/07/map-scancodes-to-keycodes/

2. 点击进入输入法（拼音/双拼）的设置页面，点击上一页和下一页里你不想要的按键修改成想要的键就行了：
  ![image](https://github.com/user-attachments/assets/ff7a2550-b1a1-4a11-a45e-77b521d81d11)

**Comment by xiaomingneo** [comment]
多谢解答！
