### ISSUE TITLE
请教大佬两个问题

### ISSUE THREAD

**Issue by pengatgstdev** [debuggerx01/fcitx5_customizer#3]
1.  fcitx5怎么设置左shift键切换输入法？
2.  fcitx5怎么设置Page Up和Page Down键上下翻页？

**Comment by debuggerx01** [comment]
![image](https://github.com/debuggerx01/fcitx5_customizer/assets/19624835/825f2d44-0907-4039-b726-f6d1e0f35822)
![image](https://github.com/debuggerx01/fcitx5_customizer/assets/19624835/03a032d4-ca94-4b10-8aee-fda89d73a726)

输入法切换按键在全局选项的最上面。
翻页有两处，一个是全局的，也在全局选项里，然后是当前输入法的，上面第二张截图是拼音的修改。
如果你是想说Mac或者Win下某些输入法，按下一页后，原本一行的候选词变成多行候选的功能，那Fcitx是不支持的。

**Comment by pengatgstdev** [comment]
谢谢大佬
