### ISSUE TITLE
大写时关闭拼音输入不起作用

### ISSUE THREAD

**Issue by pgciq** [debuggerx01/fcitx5_customizer#4]
大写开启,输入法仍然可以正常输入,日期脚本和数字转大写脚本无法启用,不知怎么回事. 
ubuntu 22.04

**Comment by pgciq** [comment]
手动安装 liblua5.3-dev 然后重启就好了,谢谢.建议脚本更新一下.

**Comment by Eplankton** [comment]
在Ubuntu 24.04上安装`sudo apt install liblua5.3-dev`之后重启，还是无效
