### ISSUE TITLE
debuggerx.com这个域名好像被屏蔽

### ISSUE THREAD

**Issue by a18ccms** [debuggerx01/fcitx5_customizer#6]
debuggerx.com这个域名好像被屏蔽了。脚本无法送上面下载资源。

**Comment by debuggerx01** [comment]
debuggerx.com域名应该是还没被屏蔽的，应该是因为解析和加速使用的cloudflare，所以可能在国内部分网络环境下有解析问题，大部分情况下应该还是“能用”的。当这个通过这个域名下载资源失败时，会尝试使用ghproxy镜像直接从github的文件服务下载资源，而正好前几天ghproxy被墙了，所以可能正好出现了你的网络环境下域名访问失败，ghproxy镜像也不能用的情况。刚刚我更新了ghproxy最新的镜像地址，理论上应该可以正常工作了，直到这些地址再次被墙……
