### ISSUE TITLE
fedora asahi 不支持

### ISSUE THREAD

**Issue by zhbityangjian** [debuggerx01/fcitx5_customizer#7]
目前本脚本只能在 debian 系 (deepin、ubuntu、mint等) 和 arch 系 (manjaro、asahi等) 发行版中运行
jack@jack-macbookpro:~/下载$

**Comment by debuggerx01** [comment]
简单适配了下，除了部分皮肤缺失，其他功能应该是好使的。
注意使用前最好安装 fcitx5-autostart 这个包。
