### ISSUE TITLE
提个 关于 标点优化的 问题，建议和其他输入法一样，增加 “`” 到 “·” 的映射。

### ISSUE THREAD

**Issue by Mirr0ch1** [debuggerx01/fcitx5_customizer#8]
启用方括号优化后，就打不出 · 了（因为 fcitx5 默认给 [ 映射到了 · ），感觉可以额外加一个规则，把 ` 键在中文模式下对应到 · 字符上面，与国产输入法们的行为一致。

**Comment by debuggerx01** [comment]
emmm，我有点纠结……因为我经常写markdown，现在可以在中文模式下直接输入'`'字符对我个人来说是很方便的，再来是到目前为止你是第一个提出需要输入'·'的人，所以感觉这个符号也不是那么常用？再来其实现在是可以利用快速输入，然后输入'*'来输入'·'的：
![image](https://github.com/debuggerx01/fcitx5_customizer/assets/19624835/b4e454f0-5e3f-4296-b60e-d7e15c9548c7)

不过你说的也有道理，既然这个脚本标榜的是“力求更符合简中用户的使用习惯”，那与国产输入法们的行为一致也无可厚非……

**Comment by Mirr0ch1** [comment]
懂了，因为我平常写 MD 代码块的时候会比较少，没有考虑到您本人的需求。

不过我已经被国产输入法训化了，现在会很自然的在准备输代码块之前 按一下 shift ，然后再去按 ` 哈哈哈哈

**Comment by debuggerx01** [comment]
最新版已支持。
